package views;

import model.Conector;
import java.sql.*;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gasler
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Index() {
        initComponents();
        setSize(410, 200);
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        campoSueldo = new javax.swing.JTextField();
        campoBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        campoPais = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 140, 90, 23);

        campoSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSueldoActionPerformed(evt);
            }
        });
        getContentPane().add(campoSueldo);
        campoSueldo.setBounds(100, 90, 260, 23);
        getContentPane().add(campoBuscar);
        campoBuscar.setBounds(100, 0, 200, 23);

        jLabel1.setText("Sueldo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 60, 20);

        jLabel2.setText("Pais:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 40, 20);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(0, 0, 90, 23);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(110, 140, 90, 23);

        btnEmail.setText("Email");
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmail);
        btnEmail.setBounds(210, 140, 90, 23);
        getContentPane().add(campoPais);
        campoPais.setBounds(100, 50, 260, 23);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 140, 77, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        try {

            Conector cn = null;
            Connection con = null;

            cn = new Conector();
            con = cn.getDriver();

            try {
                JasperReport reporte = null;
                String path = "src/report/report1.jasper";
                reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
                JasperPrint jprint = JasperFillManager.fillReport(reporte, null, con);

                JasperViewer view = new JasperViewer(jprint, false);
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
            } catch (JRException ex) {
                System.out.print(ex);
            }
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, "Error al conectar con base de datos", "ERROR!!!",
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void campoSueldoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campoSueldoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campoSueldoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed

        Conector objCn = null;
        Connection cn = null;
        PreparedStatement queri = null;
        ResultSet rows = null;

        String SQL_SELECT = "SELECT * FROM salario WHERE pais = '" + campoBuscar.getText() + "';";
        try {
            objCn = new Conector();
            cn = objCn.getDriver();
            queri = cn.prepareStatement(SQL_SELECT);
            rows = queri.executeQuery();

            while (rows.next()) {

                campoPais.setText(rows.getString("pais"));
                campoSueldo.setText(rows.getString("salario"));

            }

            JOptionPane.showMessageDialog(null, "Pais encontrado");

        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "pais no registrado", "Warnnig!!", JOptionPane.WARNING_MESSAGE);
        }

    }// GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed

        Conector objCn = null;
        Connection cn = null;
        PreparedStatement queri = null;

        String SQL_INSERT = "INSERT INTO salario(pais,salario) VALUE(?,?);";
        try {
            objCn = new Conector();
            cn = objCn.getDriver();

            String pais = campoPais.getText();
            Double sueldo = Double.parseDouble(campoSueldo.getText());

            queri = cn.prepareStatement(SQL_INSERT);
            queri.setString(1, pais);
            queri.setDouble(2, sueldo);
            queri.executeUpdate();
            JOptionPane.showMessageDialog(null, "Exito al guardar datos");

        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Error al guardar datos", "ERROR!!", JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEmailActionPerformed

        new Email(this, true).run();

    }// GEN-LAST:event_btnEmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

        campoPais.setText("");
        campoSueldo.setText("");

    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JTextField campoPais;
    private javax.swing.JTextField campoSueldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
